- hosts: terraform-ansible
  tasks:
    - name: Install python3, virtualenv
      apt: 
        pkg: 
        - python3
        - virtualenv
        update_cache: yes  
      become: yes
    - name: Install dependency with pip (Django and Django Rest)    
      pip: 
        virtualenv: /home/ubuntu/venv
        name: 
          - django
          - djangorestframework