- hosts: terraform-ansible
  tasks:
    - name: creating the file
      copy:
        dest: /home/ubuntu/index.html
        content: <h1>Done with Terraform and Ansible!</h1>
    - name: creating the server
      shell: "nohup busybox httpd -f -p 8080 &" 
